name: Deploy shiavnski-website to S3
on:
  push:
    branches: [ "main" ]
      

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout from git
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_WEBSITE_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_WEBSITE_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Build 
      run: |
           node --version
           npm install
           npm run build
           echo "Build Completed"
           aws s3 sync out s3://${{ secrets.WEBSITE_BUCKET }} --delete
           echo "Deployment to S3 Completed"
      continue-on-error: false
      
    - name: Create CloudFront invalidation
      run: aws cloudfront create-invalidation --distribution-id E36WM4GIK0ITS9 --paths "/*"
